/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import databaseHelper.ChiaSeDuLieu;
import java.awt.Dialog;
import java.awt.JobAttributes;
import java.awt.desktop.AboutEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author admin
 */
public class GiaoDienChinh_JFame extends javax.swing.JFrame {
    
    private QLSV_JPanel mnuQLSV_JPanel;
    private QLDiem_Panel mnuQLDiem_JPanel;
   
    /**
     * Creates new form GiaoDien_Form
     */
    /*
        Ngày 20/08/2022
        Xử lý khi mở giao diện chính + hiện thị form đăng nhập & độ rộng max
     */
    public GiaoDienChinh_JFame() {
        initComponents();
        setLocationRelativeTo(null);

        // Phóng to max form giao diện chính
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);

        // Xử lý khi hiện thị giao diện chính sẽ có form đăng nhập
//        DangNhap_Dialog dangNhap = new DangNhap_Dialog(this, true);
//        dangNhap.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btn_dangXuat = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btn_quanLySinhVien = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btn_quanLyDiem = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btn_gioiThieu = new javax.swing.JButton();
        tab_GDChinh = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lbl_nguoiDung = new javax.swing.JLabel();
        lbl_vaiTro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnu_dangXuat = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuFile_Exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnu_QLSV = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnu_QLDiem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnu_gioiThieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);

        btn_dangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout-icon-32.png"))); // NOI18N
        btn_dangXuat.setText("Đăng xuất");
        btn_dangXuat.setFocusable(false);
        btn_dangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_dangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_dangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangXuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_dangXuat);
        jToolBar1.add(jSeparator4);

        btn_quanLySinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/10207-man-student-light-skin-tone-icon-32.png"))); // NOI18N
        btn_quanLySinhVien.setText("Quản lý sinh viên");
        btn_quanLySinhVien.setFocusable(false);
        btn_quanLySinhVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_quanLySinhVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_quanLySinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanLySinhVienActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_quanLySinhVien);
        jToolBar1.add(jSeparator5);

        btn_quanLyDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/gpa-icon-32.png"))); // NOI18N
        btn_quanLyDiem.setText("Quản lý điểm");
        btn_quanLyDiem.setFocusable(false);
        btn_quanLyDiem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_quanLyDiem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_quanLyDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanLyDiemActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_quanLyDiem);
        jToolBar1.add(jSeparator6);

        btn_gioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-help-about-icon-32.png"))); // NOI18N
        btn_gioiThieu.setText("Giới thiệu");
        btn_gioiThieu.setFocusable(false);
        btn_gioiThieu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_gioiThieu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_gioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gioiThieuActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_gioiThieu);

        lbl_nguoiDung.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbl_nguoiDung.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lbl_vaiTro.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_vaiTro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Người dùng: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Vai trò: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_nguoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_vaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_nguoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_vaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Hệ thống");

        mnu_dangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnu_dangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Login-icon-16.png"))); // NOI18N
        mnu_dangXuat.setText("Đăng xuất");
        mnu_dangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_dangXuatActionPerformed(evt);
            }
        });
        jMenu1.add(mnu_dangXuat);
        jMenu1.add(jSeparator1);

        mnuFile_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuFile_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-edit-delete-icon-16.png"))); // NOI18N
        mnuFile_Exit.setText("Thoát");
        mnuFile_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFile_ExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnuFile_Exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");

        mnu_QLSV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnu_QLSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/10207-man-student-light-skin-tone-icon-16.png"))); // NOI18N
        mnu_QLSV.setText("Quản lý sinh viên");
        mnu_QLSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_QLSVActionPerformed(evt);
            }
        });
        jMenu2.add(mnu_QLSV);
        jMenu2.add(jSeparator2);

        mnu_QLDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/gpa-icon.png"))); // NOI18N
        mnu_QLDiem.setText("Quản lý điểm");
        mnu_QLDiem.setActionCommand("");
        mnu_QLDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_QLDiemActionPerformed(evt);
            }
        });
        jMenu2.add(mnu_QLDiem);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Trợ giúp");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Help-icon-16.png"))); // NOI18N
        jMenuItem5.setText("Nội dung");
        jMenu3.add(jMenuItem5);
        jMenu3.add(jSeparator3);

        mnu_gioiThieu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnu_gioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-help-about-icon-16.png"))); // NOI18N
        mnu_gioiThieu.setText("Giới thiệu");
        mnu_gioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_gioiThieuActionPerformed(evt);
            }
        });
        jMenu3.add(mnu_gioiThieu);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tab_GDChinh)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(52, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab_GDChinh, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnu_dangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_dangXuatActionPerformed
        // TODO add your handling code here:
        btn_dangXuatActionPerformed(evt);
    }//GEN-LAST:event_mnu_dangXuatActionPerformed

    /*
        Ngay 20/08/2022 Asg.P2: Thiết kế giao diện dạng tab và form quản lý sinh viên
        mnu_QLSV_JPanelActionPerformed duoc tao ra khi clink "quan ly sinh vien ' trong MENU
        B1. Tao truong du lieu mnuQLSV_JPanel
        B2. Neu QLSV_JPanel chua co thi tao
        B3. Tao icon cho tab_GiaoDienChinh va addTab vao
        B4. Hien thi QLSV_JPanel vua them vao tab_GiaoDienChinh
     */
    private void mnu_QLSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_QLSVActionPerformed
        mnuQLSV_JPanel = null;
        if (mnuQLSV_JPanel == null) {
            mnuQLSV_JPanel = new QLSV_JPanel();
            ImageIcon icon = new ImageIcon(getClass().getResource("/icon/10207-man-student-light-skin-tone-icon-16.png"));
            
            tab_GDChinh.addTab("Quản lý sinh viên ", icon, mnuQLSV_JPanel, "Quan ly sinh vien");
            
        }
         // tab_GDChinh.setSelectedComponent(mnuQLSV_JPanel); // Xu ly nguoi dung lick nhieu lan khi da hien thi

    }//GEN-LAST:event_mnu_QLSVActionPerformed

    private void mnu_QLDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_QLDiemActionPerformed
            mnuQLDiem_JPanel = null;
        if (mnuQLDiem_JPanel == null) {
            mnuQLDiem_JPanel = new QLDiem_Panel();
            ImageIcon icon = new ImageIcon(getClass().getResource("/icon/gpa-icon.png"));
            
            tab_GDChinh.addTab("Quản lý điểm ", icon, mnuQLDiem_JPanel, "Quản lý điểm ");
        }
        // tab_GDChinh.setSelectedComponent(mnuQLDiem_JPanel);

    }//GEN-LAST:event_mnu_QLDiemActionPerformed

    private void mnuFile_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFile_ExitActionPerformed

        System.exit(0);
    }//GEN-LAST:event_mnuFile_ExitActionPerformed

    /*
        Ngày 20/08/2022
        Xử lý sự kiện khi nhấn menu & btn giới thiệu
     */
    private void btn_gioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gioiThieuActionPerformed

        GioiThieu_Dialog gioiThieu = new GioiThieu_Dialog(this, true);
        gioiThieu.setVisible(true);

    }//GEN-LAST:event_btn_gioiThieuActionPerformed

    private void mnu_gioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_gioiThieuActionPerformed

        btn_gioiThieuActionPerformed(evt);
    }//GEN-LAST:event_mnu_gioiThieuActionPerformed

    /*
        Ngày 20/08/2022
        Asg.P3: Thiết kế form quản lý điểm, hộp thoại giới thiệu và đăng nhập
        Người dùng cần đăng nhập vào hệ thống mới dùng được chức năng đăng xuất
     */
    private void btn_dangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangXuatActionPerformed
        // TODO add your handling code here:
        DangNhap_Dialog dangNhap = new DangNhap_Dialog(this, true);
        // Cần xử lý dữ liệu sao
        dangNhap.setVisible(true);
        HienThiNguoiDangNhap();
    }//GEN-LAST:event_btn_dangXuatActionPerformed

    private void btn_quanLySinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanLySinhVienActionPerformed
        // TODO add your handling code here:
        mnu_QLSVActionPerformed(evt);
    }//GEN-LAST:event_btn_quanLySinhVienActionPerformed

    private void btn_quanLyDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanLyDiemActionPerformed
        // TODO add your handling code here:
        mnu_QLDiemActionPerformed(evt);
    }//GEN-LAST:event_btn_quanLyDiemActionPerformed

    /*
        Chức năng: Khi form chính mở mới hiển thị form đăng nhập
        Lấy ở constructor bên form chinh line 35 ở trên
     */
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        DangNhap_Dialog dangNhap = new DangNhap_Dialog(this, true);
        dangNhap.setVisible(true);
        HienThiNguoiDangNhap();
        
    }//GEN-LAST:event_formWindowOpened
    private void HienThiNguoiDangNhap(){
        lbl_nguoiDung.setText(ChiaSeDuLieu.nguoiDangNhap.getTenDangNhap());
        lbl_vaiTro.setText(ChiaSeDuLieu.nguoiDangNhap.getVaiTro());
        
        // Xử lýc phân quyền khi đăng nhập
        tab_GDChinh.removeAll();
        
        if(ChiaSeDuLieu.nguoiDangNhap.getVaiTro().equals("Giảng viên")){
            mnu_QLSV.setEnabled(true);
            mnu_QLDiem.setEnabled(false);
            btn_quanLySinhVien.setEnabled(true);
            btn_quanLyDiem.setEnabled(false);
        }else if(ChiaSeDuLieu.nguoiDangNhap.getVaiTro().equals("Đào tạo")){
            mnu_QLSV.setEnabled(false);
            mnu_QLDiem.setEnabled(true);
            btn_quanLySinhVien.setEnabled(false);
            btn_quanLyDiem.setEnabled(true);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh_JFame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh_JFame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh_JFame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh_JFame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GiaoDienChinh_JFame gdc = new GiaoDienChinh_JFame();
                
                gdc.setVisible(true);
                gdc.setDefaultCloseOperation(EXIT_ON_CLOSE);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangXuat;
    private javax.swing.JButton btn_gioiThieu;
    private javax.swing.JButton btn_quanLyDiem;
    private javax.swing.JButton btn_quanLySinhVien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbl_nguoiDung;
    private javax.swing.JLabel lbl_vaiTro;
    private javax.swing.JMenuItem mnuFile_Exit;
    private javax.swing.JMenuItem mnu_QLDiem;
    private javax.swing.JMenuItem mnu_QLSV;
    private javax.swing.JMenuItem mnu_dangXuat;
    private javax.swing.JMenuItem mnu_gioiThieu;
    private javax.swing.JTabbedPane tab_GDChinh;
    // End of variables declaration//GEN-END:variables
}
