/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import dao.BangDiemDAO;
import dao.SinhVienDAO;
import databaseHelper.KiemTraDuLieuNhapVao;
import databaseHelper.ThongBao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.BangDiem;
import model.NguoiDung;
import model.SinhVien;

/**
 *
 * @author admin
 */
public class QLDiem_Panel extends javax.swing.JPanel {

    private GiaoDienChinh_JFame gDChinh;
    private DefaultTableModel tblModel;

    /**
     * Creates new form QLDiem_Panel
     */
    public QLDiem_Panel() {
        initComponents();
        
        TaoBangDiem();
        
        TaiBangDiem();
        
    }
    
    public void TaoBangDiem(){
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{
            "Mã sinh viên", "Tiếng Anh", "Tin Học", "Điểm TB"
        });
        tbl_QLDiem.setModel(tblModel);
    }
    
    public void TaiBangDiem(){
        try {
            BangDiemDAO bdDao = new BangDiemDAO();
            List<BangDiem> list =bdDao.TimKiemDiemCaoNhat(3);
            tblModel.setRowCount(0);
            
            for (BangDiem bd : list) {
                tblModel.addRow(new Object[]{
                    bd.getMaSinhVien(), bd.getTiengAnh(), bd.getTinHoc(), bd.getTheDuc(),
                    (bd.getTiengAnh() + bd.getTinHoc() + bd.getTheDuc())/3
                });
            }
            tblModel.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
            ThongBao.ThongBaoLoi(gDChinh, e.getMessage(), "Lỗi Exception e");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_timKiem_maSinhVien = new javax.swing.JTextField();
        btn_timKiem = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_maSinhVien = new javax.swing.JTextField();
        txt_hoVaTen = new javax.swing.JTextField();
        txt_tiengAnh = new javax.swing.JTextField();
        txt_tinHoc = new javax.swing.JTextField();
        txt_theDuc = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lbl_diemTrungBinh = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btn_nhapMoi = new javax.swing.JButton();
        btn_luu = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_capNhat = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_QLDiem = new javax.swing.JTable();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Quán Lý Điểm");

        jLabel2.setText("Mã sinh viên");

        txt_timKiem_maSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timKiem_maSinhVienActionPerformed(evt);
            }
        });

        btn_timKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search-icon-16.png"))); // NOI18N
        btn_timKiem.setText("Tìm kiếm");
        btn_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_timKiem_maSinhVien, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btn_timKiem)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_timKiem_maSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_timKiem))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Mã sinh viên");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Họ và tên");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Tiếng Anh");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Tin Học");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Thể Dục");

        txt_maSinhVien.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_maSinhVienFocusLost(evt);
            }
        });

        txt_hoVaTen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_hoVaTenFocusLost(evt);
            }
        });

        txt_tiengAnh.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_tiengAnhFocusLost(evt);
            }
        });

        txt_tinHoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_tiengAnhFocusLost(evt);
            }
        });

        txt_theDuc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_tiengAnhFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_hoVaTen, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(txt_tiengAnh)
                    .addComponent(txt_tinHoc)
                    .addComponent(txt_theDuc)
                    .addComponent(txt_maSinhVien))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_maSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_hoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_tiengAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_tinHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_theDuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jLabel8.setText("Điểm trung binh");

        lbl_diemTrungBinh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_diemTrungBinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_diemTrungBinh.setText("8.5");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_diemTrungBinh)
                        .addGap(50, 50, 50))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_diemTrungBinh)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        btn_nhapMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/new-icon-16.png"))); // NOI18N
        btn_nhapMoi.setText("Nhập mới");
        btn_nhapMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nhapMoiActionPerformed(evt);
            }
        });

        btn_luu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Save-icon.png"))); // NOI18N
        btn_luu.setText("Lưu");
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });

        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-edit-delete-icon-16.png"))); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_capNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-document-edit-icon-16.png"))); // NOI18N
        btn_capNhat.setText("Cập nhật");
        btn_capNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capNhatActionPerformed(evt);
            }
        });

        tbl_QLDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_QLDiem);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                            .addComponent(jSeparator3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_nhapMoi)
                                .addGap(18, 18, 18)
                                .addComponent(btn_luu)
                                .addGap(30, 30, 30)
                                .addComponent(btn_xoa)
                                .addGap(18, 18, 18)
                                .addComponent(btn_capNhat)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)))
                .addGap(6, 6, 6))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSeparator2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(jSeparator4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_nhapMoi)
                    .addComponent(btn_luu)
                    .addComponent(btn_xoa)
                    .addComponent(btn_capNhat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_capNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capNhatActionPerformed
        btn_luuActionPerformed(evt); // Lưu với cập nhật là như nhau
    }//GEN-LAST:event_btn_capNhatActionPerformed

    private void btn_nhapMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nhapMoiActionPerformed
        txt_tiengAnh.setText("");
        txt_tinHoc.setText("");
        txt_theDuc.setText("");
        txt_hoVaTen.setText("");
        txt_maSinhVien.setText("");
        txt_timKiem_maSinhVien.setText("");
    }//GEN-LAST:event_btn_nhapMoiActionPerformed

    /*
        Ngày 21/08/2022
        Chức năng: khi click vào nút lưu
     */
    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed
        StringBuilder sb = new StringBuilder();
        KiemTraDuLieuNhapVao.KiemTraRong(txt_maSinhVien, sb, "Mã sinh viên cần phải nhập");
        KiemTraDuLieuNhapVao.KiemTraRong(txt_tiengAnh, sb, "Tiếng anh cần phải nhập");
        KiemTraDuLieuNhapVao.KiemTraRong(txt_tinHoc, sb, "Tin học cần phải nhập");
        KiemTraDuLieuNhapVao.KiemTraRong(txt_theDuc, sb, "Thể dục cần phải nhập");
        // KiemTraDuLieuNhapVao.KiemTraRong(txt_hoVaTen, sb, "Họ và tên cần phải nhập");
        // Cần kiểm tra điểm nhập vào >0 <10
        if (sb.length() > 0) {
            ThongBao.ThongBaoLoi(gDChinh, sb.toString(), "Lỗi btn_luuActionPerformed");
            return;
        }
        try {

            BangDiem bd = new BangDiem();
            bd.setMaSinhVien(txt_maSinhVien.getText());
            bd.setTiengAnh(Float.parseFloat(txt_tiengAnh.getText()));
            bd.setTinHoc(Float.parseFloat(txt_tinHoc.getText()));
            bd.setTheDuc(Float.parseFloat(txt_theDuc.getText()));

            BangDiemDAO bdDao = new BangDiemDAO();
           
            /*
                Ngày 22/08/2022
                Chức năng cập nhật sinh viên khi nguòi dùng nhấn cập nhật mà không bị trùng lắp data
            */
            if (bdDao.TimKiemBangDiem(txt_maSinhVien.getText()) != null) {
                
                if(ThongBao.ThongBaoXacNhan(gDChinh, "Bạn có muốn cập nhật bảng điểm không?", "Hỏi")== JOptionPane.NO_OPTION){
                    return;
                }
                
                if (bdDao.CapNhat(bd)) {
                    ThongBao.ThongBao(gDChinh, "Bảng điểm đã được cập nhật", "Thông báo");
                } else {
                    ThongBao.ThongBao(gDChinh, "Không cập nhật bảng điểm", "Thông báo");
                }

            } else {
                if (bdDao.Them(bd)) {
                    ThongBao.ThongBao(gDChinh, "Bảng điểm đã được lưu", "Thông báo");
                } else {
                    ThongBao.ThongBao(gDChinh, "Không thể lưu bảng điểm", "Thông báo");
                }
            }
             TaiBangDiem();
        } catch (Exception e) {
            e.printStackTrace();
            ThongBao.ThongBaoLoi(gDChinh, e.getMessage(), "Lỗi Exception e");
        }
    }//GEN-LAST:event_btn_luuActionPerformed

    private void txt_hoVaTenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_hoVaTenFocusLost

    }//GEN-LAST:event_txt_hoVaTenFocusLost

    private void txt_maSinhVienFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_maSinhVienFocusLost
               try {
            SinhVienDAO svDAO = new SinhVienDAO();
            SinhVien sv = svDAO.TimKiemSinhVien(txt_maSinhVien.getText());
            
            if(sv != null){
                txt_hoVaTen.setText(sv.getHoVaTen());
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txt_maSinhVienFocusLost

    private void txt_tiengAnhFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_tiengAnhFocusLost
        if(txt_tiengAnh.getText().equals("") || txt_tinHoc.getText().equals("") || txt_theDuc.getText().equals("")){
            return;
        }
        float tiengAnh = Float.parseFloat(txt_tiengAnh.getText());
        float tinHoc = Float.parseFloat(txt_tinHoc.getText());
        float theDuc = Float.parseFloat(txt_theDuc.getText());
        
        float avg = (tiengAnh + tinHoc + theDuc)/3;
        
        String st = String.format("%.2f", avg);
        lbl_diemTrungBinh.setText(st);
    }//GEN-LAST:event_txt_tiengAnhFocusLost

    private void txt_timKiem_maSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timKiem_maSinhVienActionPerformed
        
    }//GEN-LAST:event_txt_timKiem_maSinhVienActionPerformed

    private void btn_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timKiemActionPerformed
       try {
            BangDiemDAO bdDao = new BangDiemDAO();
            BangDiem bd = bdDao.TimKiemBangDiem(txt_timKiem_maSinhVien.getText());
            
            if(bd != null){
                txt_maSinhVien.setText(bd.getMaSinhVien());
                txt_tiengAnh.setText(String.format("%.2f", bd.getTiengAnh()));
                txt_tinHoc.setText(String.format("%.2f", bd.getTinHoc()));
                txt_theDuc.setText(String.format("%.2f", bd.getTheDuc()));
                
                txt_maSinhVienFocusLost(null);
                txt_tiengAnhFocusLost(null);
            }else{
                ThongBao.ThongBao(gDChinh, "Không tìm thấy mã sinh viên", "Thông báo");
            }
        } catch (Exception e) {
             e.printStackTrace();
            ThongBao.ThongBaoLoi(gDChinh, e.getMessage(), "Lỗi Exception e");
        }
    }//GEN-LAST:event_btn_timKiemActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        try {
            if(txt_maSinhVien.getText().equals("")){
                ThongBao.ThongBao(gDChinh, "Cần phải nhập mã sinh viên", "Lỗi");
                return;
            }
            
            BangDiemDAO bdDao = new BangDiemDAO();
            BangDiem bd = bdDao.TimKiemBangDiem(txt_maSinhVien.getText());
            
            if(bd == null){
                ThongBao.ThongBao(gDChinh, "Mã sinh viên không tồn tại trong bảng điểm", "Lỗi");
                return;
            }
            
            if(ThongBao.ThongBaoXacNhan(gDChinh, "Bạn có muốn xóa điểm của sinh viên này không?", "Hỏi")
                    == JOptionPane.NO_OPTION){
                return;
            }
            
            if(bdDao.Xoa(txt_maSinhVien.getText())){
                ThongBao.ThongBao(gDChinh, "Điểm của sinh viên đã được xóa thành công", "Thông báo");
            }else{
                ThongBao.ThongBao(gDChinh, "Không thể xóa điểm của sinh viên", "Thông báo");
            }
                
              TaiBangDiem();
        } catch (Exception e) {
             e.printStackTrace();
            ThongBao.ThongBaoLoi(gDChinh, e.getMessage(), "Lỗi Exception e");
        }
    }//GEN-LAST:event_btn_xoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_capNhat;
    private javax.swing.JButton btn_luu;
    private javax.swing.JButton btn_nhapMoi;
    private javax.swing.JButton btn_timKiem;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lbl_diemTrungBinh;
    private javax.swing.JTable tbl_QLDiem;
    private javax.swing.JTextField txt_hoVaTen;
    private javax.swing.JTextField txt_maSinhVien;
    private javax.swing.JTextField txt_theDuc;
    private javax.swing.JTextField txt_tiengAnh;
    private javax.swing.JTextField txt_timKiem_maSinhVien;
    private javax.swing.JTextField txt_tinHoc;
    // End of variables declaration//GEN-END:variables
}
