/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import dao.SinhVienDAO;
import databaseHelper.AnhDaiDien;
import databaseHelper.KiemTraDuLieuNhapVao;
import databaseHelper.ThongBao;
import java.awt.Image;
import java.io.File;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;
import model.SinhVien;

/**
 *
 * @author admin
 */
public class QLSV_JPanel extends javax.swing.JPanel {

    private GiaoDienChinh_JFame gdc;
    private DefaultTableModel tblModel;
    private byte[] anhDaiDien;

    /*
        Ngày 21/08/2022
        Chức năng: tạo bảng chứa thông tin sinh viên
     */
    private void TaoBang() {
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"Mã sinh viên", "Họ tên", "email", "Số điện thoại", "Giới tinh", "Địa chỉ"});
        tbl_sinhVien.setModel(tblModel);
    }

    /*
        Ngày 21/08/2022
        Chức năng lấy dữ liệu từ csdl lên cho bảng ở QLSV_Panel
     */
    private void LayDuLieuChoBang() {
        try {
            SinhVienDAO svDao = new SinhVienDAO();
            List<SinhVien> list = svDao.TimKiemTatCaSinhVien(); // Đọc all data

            tblModel.setRowCount(0); // Xóa các data hiện đang hiển thị trong bảng

            for (SinhVien it : list) { // Duyệt qua các sinhVien có trong ds trả về
                tblModel.addRow(new Object[]{ // Tạo dữ liệu đầu vào trong bảng
                    it.getMaSinhVien(), it.getHoVaTen(), it.getEmail(), it.getSoDienThoai(),
                    it.getGioiTinh() == 1 ? "Nam" : "Nữ", it.getDiaChi()
                });
            }
            tblModel.fireTableDataChanged(); // Đảm báo dữ liệu sau khi thay đổi sẻ đươc hiển thị
        } catch (Exception e) {
            e.printStackTrace();
            ThongBao.ThongBaoLoi(gdc, e.getMessage(), "Lỗi lấy dữ liệu cho bảng");
        }
    }

    /**
     * Creates new form QLSV_JPanel
     */
    public QLSV_JPanel() {
        initComponents();
        TaoBang();
        LayDuLieuChoBang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_maSinhVien = new javax.swing.JTextField();
        txt_hoVaTen = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_soDienThoai = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lbl_anhDaiDien = new javax.swing.JLabel();
        btn_nam = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txa_diaChi = new javax.swing.JTextArea();
        btn_nu = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_sinhVien = new javax.swing.JTable();
        btn_taoMoi = new javax.swing.JButton();
        btn_luu = new javax.swing.JButton();
        btn_capNhat = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btn_moHinh = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Quản Lý Sinh Viên");

        jLabel2.setText("Mã sinh viên");

        jLabel3.setText("Họ và tên");

        jLabel4.setText("Email");

        jLabel5.setText("Số điện thoại");

        jLabel6.setText("Giới tính");

        jLabel7.setText("Địa chỉ");

        txt_maSinhVien.setText("B1900000");
        txt_maSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maSinhVienActionPerformed(evt);
            }
        });

        txt_hoVaTen.setText("Trần Văn A");
        txt_hoVaTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hoVaTenActionPerformed(evt);
            }
        });

        txt_email.setText("email@gmail.com");

        txt_soDienThoai.setText("0869888999");
        txt_soDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_soDienThoaiActionPerformed(evt);
            }
        });

        lbl_anhDaiDien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_anhDaiDien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/10207-man-student-light-skin-tone-icon-64.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_anhDaiDien, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(lbl_anhDaiDien, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        buttonGroup1.add(btn_nam);
        btn_nam.setSelected(true);
        btn_nam.setText("Nam");

        txa_diaChi.setColumns(20);
        txa_diaChi.setRows(5);
        txa_diaChi.setText("230 - Thới Lai - Cần Thơ");
        jScrollPane1.setViewportView(txa_diaChi);

        buttonGroup1.add(btn_nu);
        btn_nu.setText("Nữ");
        btn_nu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuActionPerformed(evt);
            }
        });

        tbl_sinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_sinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_sinhVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_sinhVien);

        btn_taoMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/new-icon-16.png"))); // NOI18N
        btn_taoMoi.setText("Tạo mới");
        btn_taoMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_taoMoiActionPerformed(evt);
            }
        });

        btn_luu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Save-icon.png"))); // NOI18N
        btn_luu.setText("Lưu");
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });

        btn_capNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-document-edit-icon-16.png"))); // NOI18N
        btn_capNhat.setText("Cập nhật");
        btn_capNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capNhatActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-edit-delete-icon-16.png"))); // NOI18N
        jButton5.setText("Xóa");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btn_moHinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/open-file-icon-16.png"))); // NOI18N
        btn_moHinh.setText("Mở hình");
        btn_moHinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_moHinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(btn_taoMoi)
                                .addGap(48, 48, 48)
                                .addComponent(btn_luu)
                                .addGap(54, 54, 54)
                                .addComponent(btn_capNhat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5)
                                .addGap(46, 46, 46))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_soDienThoai))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_email)
                                            .addComponent(txt_hoVaTen)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_maSinhVien))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6))
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btn_nam)
                                                .addGap(18, 18, 18)
                                                .addComponent(btn_nu))
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_moHinh)
                                        .addGap(76, 76, 76))))))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_maSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_hoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_soDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(btn_nam)
                            .addComponent(btn_nu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_moHinh)))
                .addGap(14, 14, 14)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_luu)
                    .addComponent(btn_taoMoi)
                    .addComponent(btn_capNhat)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_maSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maSinhVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maSinhVienActionPerformed

    private void btn_nuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_nuActionPerformed

    private void txt_soDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_soDienThoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_soDienThoaiActionPerformed

    /*
        Ngày 21/08/2022
        Chức năng: Tạo mới sinh viên & Lưu sinh viên mới vào csdl
     */
    private void btn_taoMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_taoMoiActionPerformed
        // TODO add your handling code here:
        txt_maSinhVien.setText("");
        txt_hoVaTen.setText("");
        txt_soDienThoai.setText("");
        txt_email.setText("");
        txa_diaChi.setText("");

        // Xử lý phần hình ảnh khi tạo mới
        anhDaiDien = null;
        ImageIcon icon = new ImageIcon(getClass().
                getResource("/icon/10207-man-student-light-skin-tone-icon-64.png"));
        lbl_anhDaiDien.setIcon(icon);

    }//GEN-LAST:event_btn_taoMoiActionPerformed

    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed
        StringBuilder sb = new StringBuilder();
        KiemTraDuLieuNhapVao.KiemTraRong(txt_maSinhVien, sb, "Mã sinh viên không được để trống");
        KiemTraDuLieuNhapVao.KiemTraRong(txt_hoVaTen, sb, "Tên sinh viên không được để trống");
        // Kiểm tra các trường còn lại
        if (sb.length() > 0) {
            ThongBao.ThongBaoLoi(gdc, sb.toString(), "Lỗi dòng 318");
            return; // kết thúc btn_luuActionPerformed
        }
        try {
            SinhVien sv = new SinhVien();

            sv.setMaSinhVien(txt_maSinhVien.getText());
            sv.setHoVaTen(txt_hoVaTen.getText());
            sv.setEmail(txt_email.getText());
            sv.setSoDienThoai(txt_soDienThoai.getText());
            sv.setDiaChi(txa_diaChi.getText());
            sv.setGioiTinh(btn_nam.isSelected() ? 1 : 0);
            // Xử lý hình 23/08/2022
            sv.setHinhDaiDien(anhDaiDien);

            SinhVienDAO svDao = new SinhVienDAO();

            if (svDao.Them(sv)) {
                ThongBao.ThongBao(gdc, "Sinh viên đã được lưu", "Thông báo 335");
                LayDuLieuChoBang();
            } else {
                ThongBao.ThongBaoLoi(gdc, "Sinh viên KHÔNG được lưu", "Cảnh báo 337");
            }

        } catch (Exception e) {
            e.printStackTrace();
            ThongBao.ThongBaoLoi(gdc, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btn_luuActionPerformed

    private void btn_capNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capNhatActionPerformed
        StringBuilder sb = new StringBuilder();
        KiemTraDuLieuNhapVao.KiemTraRong(txt_maSinhVien, sb, "Mã sinh viên không được để trống");
        KiemTraDuLieuNhapVao.KiemTraRong(txt_hoVaTen, sb, "Tên sinh viên không được để trống");
        // Kiểm tra các trường còn lại
        if (sb.length() > 0) {
            ThongBao.ThongBaoLoi(gdc, sb.toString(), "Lỗi btn_capNhat");
            return; // kết thúc sự kiện ThongBaoLoi()
        }
        if (ThongBao.ThongBaoXacNhan(gdc, "Bạn có muốn cập nhật sinh viên không?", "Hỏi") == JOptionPane.NO_OPTION) {
            return; // Kết thúc phương thức btn_capNhatActionPerformed
        }
        try {
            SinhVien sv = new SinhVien();

            sv.setMaSinhVien(txt_maSinhVien.getText());
            sv.setHoVaTen(txt_hoVaTen.getText());
            sv.setEmail(txt_email.getText());
            sv.setSoDienThoai(txt_soDienThoai.getText());
            sv.setDiaChi(txa_diaChi.getText());
            sv.setGioiTinh(btn_nam.isSelected() ? 1 : 0);

            // Xử lý hình sau 23/08/2022
            sv.setHinhDaiDien(anhDaiDien);

            SinhVienDAO svDao = new SinhVienDAO();

            if (svDao.CapNhat(sv)) {
                ThongBao.ThongBao(gdc, "Sinh viên đã được cập nhật", "Thông báo 374 QLSV_Jpanel");
                LayDuLieuChoBang();
            } else {
                ThongBao.ThongBaoLoi(gdc, "Sinh viên KHÔNG được cập nhật", "Cảnh báo 335 QLSV_Jpanel");
            }

        } catch (Exception e) {
            e.printStackTrace();
            ThongBao.ThongBaoLoi(gdc, e.getMessage(), "Lỗi btnCapNhat");
        }
    }//GEN-LAST:event_btn_capNhatActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        StringBuilder sb = new StringBuilder();
        KiemTraDuLieuNhapVao.KiemTraRong(txt_maSinhVien, sb, "Mã sinh viên không được để trống");

        // Kiểm tra các trường còn lại
        if (sb.length() > 0) {
            ThongBao.ThongBaoLoi(gdc, sb.toString(), "Lỗi btn_capNhat");
            return; // kết thúc sự kiện ThongBaoLoi()
        }
        if (ThongBao.ThongBaoXacNhan(gdc, "Bạn có muốn xóa sinh viên không?", "Hỏi") == JOptionPane.NO_OPTION) {
            return; // Kết thúc phương thức btn_capNhatActionPerformed
        }
        try {

            SinhVienDAO svDao = new SinhVienDAO();

            if (svDao.Xoa(txt_maSinhVien.getText())) {
                ThongBao.ThongBao(gdc, "Sinh viên đã được xóa", "Thông báo 411 QLSV_Jpanel");

                btn_taoMoiActionPerformed(evt);
                LayDuLieuChoBang();
            } else {
                ThongBao.ThongBaoLoi(gdc, "Sinh viên KHÔNG được xóa", "Cảnh báo 413 QLSV_Jpanel");
            }

        } catch (Exception e) {
            e.printStackTrace();
            ThongBao.ThongBaoLoi(gdc, e.getMessage(), "Lỗi btnXoa");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txt_hoVaTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hoVaTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hoVaTenActionPerformed

    /*
        Ngày 21/08/2022
        Chức năng: Lấy dữ liệu lên khi click 1 dòng trên bảng
     */
    private void tbl_sinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_sinhVienMouseClicked
        try {
            int row = tbl_sinhVien.getSelectedRow();
            if (row >= 0) {
                String id = (String) tbl_sinhVien.getValueAt(row, 0);
                SinhVienDAO svDao = new SinhVienDAO();

                SinhVien sv = svDao.TimKiemSinhVien(id);

                if (sv != null) {
                    txt_maSinhVien.setText(sv.getMaSinhVien());
                    txt_hoVaTen.setText(sv.getHoVaTen());
                    txt_email.setText(sv.getEmail());
                    txt_soDienThoai.setText(sv.getSoDienThoai());
                    txa_diaChi.setText(sv.getDiaChi());
                    btn_nam.setSelected(sv.getGioiTinh() == 1 ? true : false);
                    
                    // Xử lý hiên thị hình đại diện khi click vào bảng Asg.P7:23/08/2022
                    if (sv.getHinhDaiDien() != null) {
                        Image img = AnhDaiDien.TaoAnhFormByteArray(sv.getHinhDaiDien(), "jpg");
                        lbl_anhDaiDien.setIcon(new ImageIcon(img));
                        anhDaiDien = sv.getHinhDaiDien();

                    } else {
                        anhDaiDien = sv.getHinhDaiDien();
                        ImageIcon icon = new ImageIcon(getClass().
                                getResource("/icon/10207-man-student-light-skin-tone-icon-64.png"));
                        lbl_anhDaiDien.setIcon(icon);
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            ThongBao.ThongBaoLoi(gdc, e.getMessage(), "Lỗi tbl_sinhVienMouseClicked");
        }
    }//GEN-LAST:event_tbl_sinhVienMouseClicked

    private void btn_moHinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_moHinhActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File f) {
                if (f.isDirectory()) {
                    return true;
                } else {
                    return f.getName().toLowerCase().endsWith(".jpg");
                }
            }

            @Override
            public String getDescription() {
                return "Image File (*.jpg)";
            }
        });
        if (chooser.showOpenDialog(gdc) == JFileChooser.CANCEL_OPTION) {
            return;
        }
        File file = chooser.getSelectedFile();
        try {
            ImageIcon icon = new ImageIcon(file.getPath());
            Image img = AnhDaiDien.ThayDoiKichThuoc(icon.getImage(), 140, 160);
            ImageIcon thayDoiKichThuocIcon = new ImageIcon(img);
            lbl_anhDaiDien.setIcon(thayDoiKichThuocIcon);

            anhDaiDien = AnhDaiDien.toByteArray(img, "jpg");

        } catch (Exception e) {
            e.printStackTrace();
            ThongBao.ThongBaoLoi(gdc, e.getMessage(), "Lỗi btn_moHinhActionPerformed");
        }

    }//GEN-LAST:event_btn_moHinhActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_capNhat;
    private javax.swing.JButton btn_luu;
    private javax.swing.JButton btn_moHinh;
    private javax.swing.JRadioButton btn_nam;
    private javax.swing.JRadioButton btn_nu;
    private javax.swing.JButton btn_taoMoi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbl_anhDaiDien;
    private javax.swing.JTable tbl_sinhVien;
    private javax.swing.JTextArea txa_diaChi;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_hoVaTen;
    private javax.swing.JTextField txt_maSinhVien;
    private javax.swing.JTextField txt_soDienThoai;
    // End of variables declaration//GEN-END:variables
}
